### ISSUE TITLE
No cache file given

### ISSUE THREAD

**Issue by pintail-xyz** [anson-vandoren/binance-downloader#2]
Running on Ubuntu I followed the install instructions and all dependencies seemed to install correctly but when I run `kline-binance --help` I get the error `kline-binance: command not found.`

Is there something that needs to be added to my PATH or anything else that might be preventing me using this command?

---

Edit - OK I was able to get it to run by using `poetry run kline-binance` and it appears to successfully fetch the data from binance, but then I get the error `ValueError: No cache file given, cannot write to HDF` and it fails to save the data.

---

Edit 2 - Eventually it worked when I included a cache file name at line 85 of cli.py and created a downloaded folder.

**Comment by anson-vandoren** [comment]
@bluepintail sorry, I pushed a few commits that weren't ready for prime time. Will have a working version up later today

**Comment by anson-vandoren** [comment]
Resolved in 110ac35e19142e59bb649dea8fd7f95d2b340a36

Please let me know if you're still having issues

**Comment by pintail-xyz** [comment]
Thanks. I just did a fresh install but now when I try and run I get:

`NOTICE: util: Error reading JSON from cache/earliest_timestamps.json`

I've checked in the binance_downloader/cache folder and there's no earliest_timestamps.json file.

**Comment by anson-vandoren** [comment]
I will change the wording to be less confusing, but the downloader should have still run normally. That's just letting you know there wasn't already cached data, and it pulled earliest timestamp for that currency pair from the server instead of using a cached value.

If it failed to download, can you send the rest of the output after the above NOTICE line?

Thanks

**Comment by pintail-xyz** [comment]
Ah OK, here's the full trace:
```
NOTICE: util: Error reading JSON from cache/earliest_timestamps.json
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/binance-downloader/binance_downloader/cli.py", line 84, in main
    binance.fetch_parallel()
  File "/home/user/binance-downloader/binance_downloader/api.py", line 65, in fetch_parallel
    ranges = self._get_chunk_ranges()
  File "/home/user/binance-downloader/binance_downloader/api.py", line 165, in _get_chunk_ranges
    period_start = self._get_valid_start()
  File "/home/user/binance-downloader/binance_downloader/api.py", line 195, in _get_valid_start
    earliest = binance_utils.earliest_valid_timestamp(self.symbol, self.interval)
  File "/home/user/binance-downloader/binance_downloader/binance_utils.py", line 268, in earliest_valid_timestamp
    prev_json[identifier] = earliest_timestamp
TypeError: 'NoneType' object does not support item assignment
```

**Comment by pintail-xyz** [comment]
I was able to get it to work when I copied the `earliest_timestamps.json` file from the previous installation and I also had to manually create the `downloaded` folder.

**Comment by anson-vandoren** [comment]
Thanks. I think I have an idea of what the issue might be. Will take a look at the code tonight and have a fix soon.

**Comment by anson-vandoren** [comment]
Fixed and tested with a missing `earliest_timestamps.json`

Thanks, and let me know if you spot any other issues.
